# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'coforms',
            },
        ),
    ]
